### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by kryptag** [cph-cs241/UFO_Compilation#1]
#### Score :7 

review based on this version [https://github.com/cph-cs241/UFO_Compilation/blob/f960f1d1a24adad4617e481cba6d11bb5a21267b/Blog/README.md](url)

The topic of monitoring is followed thoroughly, and it's very easy to follow the flow. I like the reuse of the `Bat analogy` it really flows into itself well as you expand the analogy.

For the general overview is quite nice and it's easy to follow and understand

**Comment by astyltsvig** [comment]
Thank you for the review.
