### ISSUE TITLE
Reliable Data from Credible Sources

### ISSUE THREAD

**Issue by Ekskursantas** [cph-cs241/UFO_Compilation#2]
#### Score: 7
review based on [this](https://github.com/cph-cs241/UFO_Compilation/blob/f960f1d1a24adad4617e481cba6d11bb5a21267b/Blog/README.md) version

While reading the blog I felt like I was missing some direct references. Yes, there is a Reference paragraph and I can find all the references needed, but while reading I was missing some sort of direct relation to the paragraph, so let's say if I am interested in a sentence or paragraph and I would like to read about it a bit more I would like to know right there and then in some way that if I wanna know more about it I have to go to some specific reference or so.

**Comment by astyltsvig** [comment]
Hello!
Thank you for the review, and yes i agree with you on that. We will add references on some sections where we feel readers could read more about.

**Comment by Ekskursantas** [comment]
Perfecto!
