### ISSUE TITLE
Design Criteria, Sample Calculations and Simulations

### ISSUE THREAD

**Issue by kryptag** [cph-cs241/UFO_Compilation#5]
#### Score :10

review based on [this](https://github.com/cph-cs241/UFO_Compilation/blob/f960f1d1a24adad4617e481cba6d11bb5a21267b/Blog/README.md) version

When it comes to the experiments conducted in this blog, i can only say that not a single piece is missing. It's fulfilling and shows be every step i need to take to reproduce the same setup. There is no parts missing or questions that come up that aren't answered directly by the author or in the references. My only "issue" is that experiments is not a part of the main blog, but i believe this might be an issue with how it the blog was created and not as much a direct choice. to improve this i would like to have the `experiments.md` be a part of the main blog

**Comment by astyltsvig** [comment]
Due to Caroline feedback, we choose to keep experiment in a seperate md file.
